### ISSUE TITLE
Invalid character in stanza

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/tigase-extension#28]
It seems like setting the table encoding to utf8mb4 wasn't enough...

```
2015-03-04 20:46:25.027 [in_9-sess-man]    JDBCRepository.addDataList()       WARNING:  Error adding data list, user_id: xxxxxx@beta.kontalk.net, subnode: offline/msgoffline, key: messages, uid: 183, nid: 420, list: [<message type="chat" xmlns="jabber:client" from="xxxx@beta.kontalk.net/xxxxxx" id="yve5jL0QynUf3eZ38Eq9w2CRk60dRD" to="xxxxx@beta.kontalk.net"><body>😉</body><active xmlns="http://jabbr.org/protocol/chatstates"/><request xmlns="urn:xmpp:receipts"/><delay from="beta.kontalk.net" stamp="2015-03-04T20:46:25.023Z" xmlns="urn:xmpp:delay">Offline Storage - beta.kontalk.net</delay></message>]
java.sql.SQLException: Incorrect string value: '\xF0\x9F\x98\x89</...' for column 'pval' at row 1
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
        at tigase.db.jdbc.JDBCRepository.addDataList(JDBCRepository.java:180)
        at tigase.db.jdbc.JDBCRepository.addDataList(JDBCRepository.java:200)
        at tigase.db.UserRepositoryMDImpl.addDataList(UserRepositoryMDImpl.java:63)
        at tigase.db.NonAuthUserRepositoryImpl.addOfflineDataList(NonAuthUserRepositoryImpl.java:101)
        at tigase.xmpp.impl.OfflineMessages$MsgRepositoryImpl.storeMessage(OfflineMessages.java:506)
        at tigase.xmpp.impl.OfflineMessages.savePacketForOffLineUser(OfflineMessages.java:301)
        at tigase.xmpp.impl.OfflineMessages.postProcess(OfflineMessages.java:151)
```

**Comment by daniele-athome** [comment]
Fixed by upgrading mysql-connector to latest version.
