### ISSUE TITLE
error when connection tigase-server

### ISSUE THREAD

**Issue by geass** [kontalk/tigase-extension#47]
Hi, 

i made all of setup as u described on wiki -setup for local- and change to my server ips.But when i can get "request verification code" im getting that error :

 2629-2728/? W/ActivityManager﹕ Activity stop timeout for ActivityRecord{125b077 u0 com.foursquare.robin/.activities.MainActivity t461}
07-26 00:45:49.537  19509-19574/? W/NumberValidator﹕ connection error - trying next server in list
    org.jivesoftware.smack.SmackException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
            at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1008)
            at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$200(XMPPTCPConnection.java:935)
            at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:950)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
            at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:322)
            at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:623)
            at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:585)
            at org.jivesoftware.smack.tcp.XMPPTCPConnection.initReaderAndWriter(XMPPTCPConnection.java:642)
            at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:742)
            at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$900(XMPPTCPConnection.java:139)
            at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1001)
            at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$200(XMPPTCPConnection.java:935)
            at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:950)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
            at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318)
            at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219)
            at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:114)
            at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:550)
            at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)

**Comment by daniele-athome** [comment]
Please direct these kind of questions to kontalk-devel@googlegroups.com (or through here https://groups.google.com/forum/#!forum/kontalk-devel).
You're using a self-signed certificate most probably. Enable "Accept any SSL certificate" in the app.
