### ISSUE TITLE
Caused by tigase.messages Table

### ISSUE THREAD

**Issue by puyide** [kontalk/tigase-extension#55]
HI
   OfflineMessages not init。we have messages Table?

```
  at org.kontalk.xmppserver.messages.JDBCMsgRepository.expireMessages(JDBCMsgRepository.java:84)
        at org.kontalk.xmppserver.messages.OfflineMessages$1.run(OfflineMessages.java:121)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2015-10-26 01:58:16.013 [msgoffline2 tasks]  OfflineMessages$1.run()          WARNING:  error purging expired messages
tigase.db.TigaseDBException: database error
        at org.kontalk.xmppserver.messages.JDBCMsgRepository.expireMessages(JDBCMsgRepository.java:87)
        at org.kontalk.xmppserver.messages.OfflineMessages$1.run(OfflineMessages.java:121)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'tigase.messages' doesn't exist
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
```

**Comment by daniele-athome** [comment]
Sorry, I forgot to upload the script. I've just uploaded it to the data directory, messages.sql.

**Comment by puyide** [comment]
Thank you very much for your reply~！Daniele Ricci.
